# **Non Graded Challenge 8**

## **Objective**

This Non Graded Challenge was created to evaluate the concept of Pandas with the aim of:

1. Able to load data with Pandas

2. Able to handle missing values in the dataset

3. Able to perform column manipulation

4. Able to make queries on the dataset

5. Able to perform grouping on the dataset3

### **INTRODUCTION**

The introduction section must contain the identity, background of the problem, and the problem statement to be discussed.

### **IMPORTING LIBRARIES**

The first cell in the notebook must contain and only contain all the libraries used in the project.

In [57]:
# Importing pandas
import pandas as pd

### **DATA LOADING**

This section contains the queries that have been created and the data loading process, followed by simple data exploration.

In [78]:
# Importing the data

data = pd.read_csv("https://github.com/FTDS-learning-materials/phase-0/raw/main/src/data_ngc.csv")
data.shape
data.head()

,province_state,country_region,date,latitude,longitude,location_geom,confirmed,deaths,recovered,active,fips,admin2,combined_key
0,NaN,Malaysia,2020-03-08,2.5000,112.5000,POINT(112.5 2.5),99.0,0.0,24.0,NaN,NaN,NaN,NaN
1,NaN,Malaysia,2020-03-10,2.5000,112.5000,POINT(112.5 2.5),129.0,0.0,24.0,NaN,NaN,NaN,NaN
2,NaN,Singapore,2020-03-13,1.3521,103.8198,POINT(103.8198 1.3521),200.0,0.0,97.0,NaN,NaN,NaN,NaN
3,NaN,Malaysia,2020-03-13,4.2105,101.9758,POINT(101.9758 4.2105),197.0,0.0,26.0,NaN,NaN,NaN,NaN
4,NaN,Malaysia,2020-03-15,4.2105,101.9758,POINT(101.9758 4.2105),428.0,0.0,42.0,NaN,NaN,NaN,NaN

### **DATA CLEANING**

This section contains the data preparation process, such as data cleaning, before further data exploration. 

The cleaning process may include assigning new names to each column, filling in missing values, deleting unused columns, and so on.

In [79]:
data.describe()

,latitude,longitude,confirmed,deaths,recovered,active,fips,admin2
count,11321.000000,11321.000000,1.192900e+04,11913.000000,1.640000e+03,1520.000000,0.0,0.0
mean,3.379857,104.916649,5.691680e+05,10294.111223,2.942046e+05,43025.965132,NaN,NaN
std,2.163091,5.239123,1.245387e+06,33496.371144,5.221845e+05,81075.148339,NaN,NaN
min,-0.789300,100.204800,0.000000e+00,0.000000,0.000000e+00,0.000000,NaN,NaN
25%,1.553300,101.686900,5.980000e+04,197.000000,8.820000e+03,436.000000,NaN,NaN
50%,3.139000,102.250100,2.019620e+05,1424.000000,5.873950e+04,11307.500000,NaN,NaN
75%,5.311700,103.833300,3.570460e+05,2764.000000,3.259220e+05,57167.500000,NaN,NaN
max,6.444900,116.075300,6.738225e+06,624641.000000,2.907920e+06,574135.000000,NaN,NaN

In [80]:
data.isnull()

,province_state,country_region,date,latitude,longitude,location_geom,confirmed,deaths,recovered,active,fips,admin2,combined_key
0,True,False,False,False,False,False,False,False,False,True,True,True,True
1,True,False,False,False,False,False,False,False,False,True,True,True,True
2,True,False,False,False,False,False,False,False,False,True,True,True,True
3,True,False,False,False,False,False,False,False,False,True,True,True,True
4,True,False,False,False,False,False,False,False,False,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11925,False,False,False,False,False,False,False,False,True,True,True,True,False
11926,False,False,False,False,False,False,False,False,True,True,True,True,False
11927,False,False,False,False,False,False,False,False,True,True,True,True,False
11928,False,False,False,False,False,False,False,False,True,True,True,True,False
11929,False,False,False,False,False,False,False,False,True,True,True,True,False

In [81]:
# Changing the date column type from object to 
data['date'] = pd.to_datetime(data['date'])
data['date']

0       2020-03-08
1       2020-03-10
2       2020-03-13
3       2020-03-13
4       2020-03-15
           ...
11925   2022-06-02
11926   2022-04-29
11927   2022-01-10
11928   2023-02-25
11929   2022-09-29
Name: date, Length: 11930, dtype: datetime64[ns]

In [82]:
# Dropping 2 column that only have NaN values

data_new = data.drop(columns=['fips','admin2'])

In [83]:
data_new.head()

,province_state,country_region,date,latitude,longitude,location_geom,confirmed,deaths,recovered,active,combined_key
0,NaN,Malaysia,2020-03-08,2.5000,112.5000,POINT(112.5 2.5),99.0,0.0,24.0,NaN,NaN
1,NaN,Malaysia,2020-03-10,2.5000,112.5000,POINT(112.5 2.5),129.0,0.0,24.0,NaN,NaN
2,NaN,Singapore,2020-03-13,1.3521,103.8198,POINT(103.8198 1.3521),200.0,0.0,97.0,NaN,NaN
3,NaN,Malaysia,2020-03-13,4.2105,101.9758,POINT(101.9758 4.2105),197.0,0.0,26.0,NaN,NaN
4,NaN,Malaysia,2020-03-15,4.2105,101.9758,POINT(101.9758 4.2105),428.0,0.0,42.0,NaN,NaN

In [84]:
data_new['province_state'].value_counts()

province_state
Unknown              534
W.P. Labuan          534
Johor                534
Sabah                534
Kedah                534
W.P. Kuala Lumpur    534
W.P. Putrajaya       534
Melaka               534
Perak                534
Negeri Sembilan      534
Terengganu           534
Kelantan             534
Sarawak              534
Pulau Pinang         534
Perlis               534
Selangor             534
Pahang               534
Name: count, dtype: int64

In [85]:
data_new['country_region'].value_counts()

country_region
Malaysia     9685
Singapore    1142
Indonesia    1103
Name: count, dtype: int64

In [86]:
data_new['date'].value_counts()

date
2022-07-26    19
2022-04-19    19
2022-07-27    19
2021-09-22    19
2021-11-09    19
              ..
2020-02-28     2
2020-02-07     2
2020-02-21     2
2020-01-28     2
2020-01-24     1
Name: count, Length: 1142, dtype: int64

In [87]:
data_new['location_geom'].value_counts()

location_geom
POINT(113.9213 -0.7893)       1103
POINT(103.8333 1.2833)        1095
POINT(101.975766 4.210484)     549
POINT(103.7618 1.4854)         534
POINT(116.0753 5.9788)         534
POINT(100.3685 6.1184)         534
POINT(101.6869 3.139)          534
POINT(101.6964 2.9264)         534
POINT(102.2501 2.1896)         534
POINT(115.2308 5.2831)         534
POINT(101.0901 4.5921)         534
POINT(103.3256 3.8126)         534
POINT(103.1324 5.3117)         534
POINT(102.2381 6.1254)         534
POINT(110.3592 1.5533)         534
POINT(100.3288 5.4141)         534
POINT(100.2048 6.4449)         534
POINT(101.5183 3.0738)         534
POINT(101.9424 2.7258)         534
POINT(112.5 2.5)                12
POINT(103.8198 1.3521)           9
POINT(101.9758 4.2105)           9
Name: count, dtype: int64

In [88]:
data_new['confirmed'].value_counts()

confirmed
0.0          534
2222006.0     15
22955.0       14
6056017.0     12
22.0          12
            ...
254245.0       1
247171.0       1
258526.0       1
173557.0       1
177522.0       1
Name: count, Length: 11001, dtype: int64

In [89]:
data_new['combined_key'].value_counts()

combined_key
Indonesia                      1083
Singapore                      1083
Malaysia                        549
Perak, Malaysia                 534
Johor, Malaysia                 534
Sabah, Malaysia                 534
Kedah, Malaysia                 534
W.P. Kuala Lumpur, Malaysia     534
W.P. Putrajaya, Malaysia        534
Melaka, Malaysia                534
W.P. Labuan, Malaysia           534
Unknown, Malaysia               534
Negeri Sembilan, Malaysia       534
Terengganu, Malaysia            534
Kelantan, Malaysia              534
Sarawak, Malaysia               534
Pulau Pinang, Malaysia          534
Perlis, Malaysia                534
Selangor, Malaysia              534
Pahang, Malaysia                534
Name: count, dtype: int64

### **DATA EXPLORATION**

This section contains data exploration on the dataset above using queries, grouping, and so on.

### **CONCLUSION**

In this final section, there must be conclusions that reflect the results obtained by comparing them with the problem statement written in the introduction section.